# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-tables}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nicholas Wright"]
  s.date = %q{2010-02-13}
  s.description = %q{A table data structure implemented in ruby}
  s.email = %q{nick.loves.rails@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "lib/table.rb",
     "spec/spec_helper.rb",
     "spec/table_spec.rb"
  ]
  s.homepage = %q{http://github.com/Abica/ruby-tables}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby implementation of lua tables}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/table_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.2"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.2"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.2"])
  end
end

